/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcabecalho = new javax.swing.JLabel();
        jtaba = new javax.swing.JTabbedPane();
        jpprimeiraaba = new javax.swing.JPanel();
        jptestesplitpanel = new javax.swing.JPanel();
        jptestecombobox = new javax.swing.JPanel();
        jptestejtable = new javax.swing.JPanel();
        jptestejradiobutton = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela");
        setResizable(false);

        lbcabecalho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbcabecalho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbcabecalho.setText("Projeto Swing - Cabeçalho do Aplicativo");

        jtaba.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtaba.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jtaba.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jpprimeiraabaLayout = new javax.swing.GroupLayout(jpprimeiraaba);
        jpprimeiraaba.setLayout(jpprimeiraabaLayout);
        jpprimeiraabaLayout.setHorizontalGroup(
            jpprimeiraabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jpprimeiraabaLayout.setVerticalGroup(
            jpprimeiraabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jtaba.addTab("Primeira Aba", jpprimeiraaba);

        javax.swing.GroupLayout jptestesplitpanelLayout = new javax.swing.GroupLayout(jptestesplitpanel);
        jptestesplitpanel.setLayout(jptestesplitpanelLayout);
        jptestesplitpanelLayout.setHorizontalGroup(
            jptestesplitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jptestesplitpanelLayout.setVerticalGroup(
            jptestesplitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jtaba.addTab("Teste SplitPane", jptestesplitpanel);

        javax.swing.GroupLayout jptestecomboboxLayout = new javax.swing.GroupLayout(jptestecombobox);
        jptestecombobox.setLayout(jptestecomboboxLayout);
        jptestecomboboxLayout.setHorizontalGroup(
            jptestecomboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jptestecomboboxLayout.setVerticalGroup(
            jptestecomboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jtaba.addTab("Teste ComboBox", jptestecombobox);

        javax.swing.GroupLayout jptestejtableLayout = new javax.swing.GroupLayout(jptestejtable);
        jptestejtable.setLayout(jptestejtableLayout);
        jptestejtableLayout.setHorizontalGroup(
            jptestejtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jptestejtableLayout.setVerticalGroup(
            jptestejtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jtaba.addTab("Teste JTable", jptestejtable);

        javax.swing.GroupLayout jptestejradiobuttonLayout = new javax.swing.GroupLayout(jptestejradiobutton);
        jptestejradiobutton.setLayout(jptestejradiobuttonLayout);
        jptestejradiobuttonLayout.setHorizontalGroup(
            jptestejradiobuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jptestejradiobuttonLayout.setVerticalGroup(
            jptestejradiobuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jtaba.addTab("Teste JRadioButton", jptestejradiobutton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbcabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtaba))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbcabecalho)
                .addGap(18, 18, 18)
                .addComponent(jtaba, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpprimeiraaba;
    private javax.swing.JPanel jptestecombobox;
    private javax.swing.JPanel jptestejradiobutton;
    private javax.swing.JPanel jptestejtable;
    private javax.swing.JPanel jptestesplitpanel;
    private javax.swing.JTabbedPane jtaba;
    private javax.swing.JLabel lbcabecalho;
    // End of variables declaration//GEN-END:variables
}
